import { Request, Response } from 'express';
import catchAsync from '../../../utils/catchAsync';
import sendResponse from '../../../utils/sendResponse';
import * as AIService from './ai.service';
import { Types } from 'mongoose';
import Lesson from '../microLessons/lesson.model';
import { Course, Enrollment } from '../course/course.model';

/**
 * Generate Lesson with AI
 */
export const generateLesson = catchAsync(async (req: Request, res: Response) => {
  const userId = new Types.ObjectId(req.user!.userId);
  const aiResult = await AIService.generateLesson(userId, req.body);

  // Get or create "AI Generated Lessons" course
  let aiCourse = await Course.findOne({ 
    title: 'AI Generated Lessons',
    isAIGenerated: true 
  });

  if (!aiCourse) {
    aiCourse = await Course.create({
      title: 'AI Generated Lessons',
      description: 'A collection of personalized lessons generated by AI based on your learning interests',
      author: userId,
      topic: 'Mixed Topics',
      difficulty: 'beginner',
      estimatedDuration: 0,
      isPublished: true,
      isAIGenerated: true,
      isPremium: false,
      price: 0,
    });
  }

  // Auto-enroll user in AI Generated Lessons course if not already enrolled
  const existingEnrollment = await Enrollment.findOne({
    user: userId,
    course: aiCourse._id,
  });

  if (!existingEnrollment) {
    await Enrollment.create({
      user: userId,
      course: aiCourse._id,
      progress: 0,
      completedLessons: [],
      startedAt: new Date(),
    });
    
    // Increment enrolled count
    aiCourse.enrolledCount += 1;
    await aiCourse.save();
  }

  // Create the lesson in database
  const savedLesson = await Lesson.create({
    title: aiResult.title,
    description: aiResult.summary || aiResult.content.substring(0, 200),
    content: aiResult.content,
    topic: req.body.topic,
    tags: aiResult.keyPoints || [],
    difficulty: aiResult.difficulty || 'beginner',
    estimatedTime: aiResult.estimatedDuration || 10,
    aiSummary: aiResult.summary,
    keyPoints: aiResult.keyPoints || [],
    aiGenerated: true,
    author: userId,
    course: aiCourse._id,
    isPublished: true,
    order: await Lesson.countDocuments({ course: aiCourse._id }),
  });

  sendResponse(res, {
    statusCode: 201,
    success: true,
    message: 'AI lesson generated and saved successfully',
    data: savedLesson,
  });
});

/**
 * Generate Quiz with AI
 */
export const generateQuiz = catchAsync(async (req: Request, res: Response) => {
  const userId = new Types.ObjectId(req.user!.userId);
  const result = await AIService.generateQuiz(userId, req.body);

  sendResponse(res, {
    statusCode: 201,
    success: true,
    message: 'AI quiz generated successfully',
    data: result,
  });
});

/**
 * Generate Flashcards with AI
 */
export const generateFlashcards = catchAsync(async (req: Request, res: Response) => {
  const userId = new Types.ObjectId(req.user!.userId);
  const result = await AIService.generateFlashcards(userId, req.body);

  sendResponse(res, {
    statusCode: 201,
    success: true,
    message: 'AI flashcards generated successfully',
    data: result,
  });
});

/**
 * Chat with AI Tutor
 */
export const chat = catchAsync(async (req: Request, res: Response) => {
  const userId = new Types.ObjectId(req.user!.userId);
  const result = await AIService.chat(userId, req.body);

  sendResponse(res, {
    statusCode: 200,
    success: true,
    message: 'AI response generated successfully',
    data: result,
  });
});

/**
 * Get Chat Sessions
 */
export const getChatSessions = catchAsync(async (req: Request, res: Response) => {
  const userId = new Types.ObjectId(req.user!.userId);
  const page = parseInt(req.query.page as string) || 1;
  const limit = parseInt(req.query.limit as string) || 20;

  const result = await AIService.getChatSessions(userId, page, limit);

  sendResponse(res, {
    statusCode: 200,
    success: true,
    message: 'Chat sessions retrieved successfully',
    data: result.sessions,
    meta: {
      page: result.pagination.currentPage,
      limit: result.pagination.itemsPerPage,
      total: result.pagination.totalItems,
    },
  });
});

/**
 * Get Chat Session Details
 */
export const getChatSessionDetails = catchAsync(async (req: Request, res: Response) => {
  const userId = new Types.ObjectId(req.user!.userId);
  const { sessionId } = req.params;

  const result = await AIService.getChatSessionDetails(userId, sessionId);

  sendResponse(res, {
    statusCode: 200,
    success: true,
    message: 'Chat session details retrieved successfully',
    data: result,
  });
});

/**
 * Delete Chat Session
 */
export const deleteChatSession = catchAsync(async (req: Request, res: Response) => {
  const userId = new Types.ObjectId(req.user!.userId);
  const { sessionId } = req.params;

  const result = await AIService.deleteChatSession(userId, sessionId);

  sendResponse(res, {
    statusCode: 200,
    success: true,
    message: result.message,
    data: null,
  });
});

/**
 * Improve Content with AI
 */
export const improveContent = catchAsync(async (req: Request, res: Response) => {
  const userId = new Types.ObjectId(req.user!.userId);
  const result = await AIService.improveContent(userId, req.body);

  sendResponse(res, {
    statusCode: 200,
    success: true,
    message: 'Content improved successfully',
    data: result,
  });
});

/**
 * Get Topic Suggestions
 */
export const getTopicSuggestions = catchAsync(async (req: Request, res: Response) => {
  const userId = new Types.ObjectId(req.user!.userId);
  const skillLevel = req.query.skillLevel as 'beginner' | 'intermediate' | 'advanced' | undefined;
  const limit = parseInt(req.query.limit as string) || 10;

  const result = await AIService.getTopicSuggestions(userId, { skillLevel, limit });

  sendResponse(res, {
    statusCode: 200,
    success: true,
    message: 'Topic suggestions retrieved successfully',
    data: result,
  });
});

/**
 * Get AI Statistics
 */
export const getAIStats = catchAsync(async (req: Request, res: Response) => {
  const userId = new Types.ObjectId(req.user!.userId);
  const result = await AIService.getAIStats(userId);

  sendResponse(res, {
    statusCode: 200,
    success: true,
    message: 'AI statistics retrieved successfully',
    data: result,
  });
});

/**
 * Get Generation History
 */
export const getGenerationHistory = catchAsync(async (req: Request, res: Response) => {
  const userId = new Types.ObjectId(req.user!.userId);
  const page = parseInt(req.query.page as string) || 1;
  const limit = parseInt(req.query.limit as string) || 20;
  const type = req.query.type as 'lesson' | 'quiz' | 'flashcard' | 'chat' | undefined;
  const status = req.query.status as 'success' | 'failed' | 'pending' | undefined;

  const result = await AIService.getGenerationHistory(userId, page, limit, type, status);

  sendResponse(res, {
    statusCode: 200,
    success: true,
    message: 'Generation history retrieved successfully',
    data: result.history,
    meta: {
      page: result.pagination.currentPage,
      limit: result.pagination.itemsPerPage,
      total: result.pagination.totalItems,
    },
  });
});
